AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Deploy a Fargate task that uses hey to generate parallel concurrent traffic
Parameters:
  URL:
    Type: String
    Description: Url for load test

Resources:
  # ECS Loadtest Task Execution Role
  ECSLoadTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: [ecs-tasks.amazonaws.com]
            Action: ["sts:AssumeRole"]
      Path: /
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy"

  # Fargate Task
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: "yelb-loadtest"
      NetworkMode: awsvpc
      Cpu: "256"
      Memory: "512"
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref "ECSLoadTaskExecutionRole"
      ContainerDefinitions:
        - Name: yelb-loadtest
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/hey-loadtest:latest
          Command:
            - -c
            - 100
            - -n
            - 10000
            - -z
            - 2m
            - !Sub "${URL}"
          LogConfiguration:
            LogDriver: "awslogs"
            Options:
              awslogs-group: ecs/serviceconnectdemo
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "loadtest"
